- id: 'wake_up_light_automation'
  alias: "Déclencher le Réveil Lumineux"
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: template
      value_template: >
        {{ states('sensor.time') == (state_attr('input_datetime.wake_up_time', 'timestamp') | timestamp_custom('%H:%M', False)) }}
    - condition: state
      entity_id: input_boolean.wake_up_alarm
      state: 'on'
  action:
    - service: script.turn_on
      target:
        entity_id: script.wake_up_light
